/**
 * Where a rule's documentation lives.
 *
 * Editors show this on hover and behind "show documentation", so it points at
 * the rule's own page rather than at a shared anchor. The pages under
 * `docs/rules/` are generated by `scripts/gen-rule-docs.mjs`, and CI fails when
 * they drift, so a URL built here always resolves.
 */
const BASE = "https://github.com/swissspidy/playwright-webmcp/blob/main/docs/rules";

/** @param id the rule id without the `webmcp/` prefix, e.g. `tool-name-valid`. */
export function ruleDocsUrl(id: string): string {
  return `${BASE}/${id}.md`;
}
